const fs = require('fs');
const path = require('path');
require('dotenv').config();

const targetPath = path.join(
  __dirname,
  '../apps/dashboard/environments/environment.ts',
);

const apiHost = process.env.API_HOST || 'localhost';
const apiPort = process.env.API_PORT || '3000';
const isProduction = process.env.NODE_ENV === 'production';
const protocol = process.env.API_PROTOCOL || 'http';
const apiUrl = `${protocol}://${apiHost}:${apiPort}/api`;
const envConfigFile = `
/* THIS FILE IS AUTO-GENERATED BY tools/set-env.js 
  DO NOT EDIT MANUALLY, update .env instead
*/
export const environment = {
  production: ${isProduction},
  apiUrl: '${apiUrl}',
};
`;

fs.writeFile(targetPath, envConfigFile, function (err: unknown): void {
  if (err) {
    console.log('Error writing environment file:', err);
  } else {
    console.log(`Environment file generated at ${targetPath}`);
    console.log(`API URL: ${apiUrl}`);
  }
});
